version: "3"

tasks:
  tidy:
    cmds:
      - go mod tidy

  build:
    cmds:
      - mkdir -p bin
      - go build -o ./bin/picoclaw-memory ./cmd/server

  run:
    cmds:
      - go run ./cmd/server

  test:
    cmds:
      - go test ./...

  docker-build:
    cmds:
      - docker build -t picoclaw-memory .
